apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: applications
  namespace: openshift-gitops
  labels:
    test: scale
spec:
  project: default
  source:
    repoURL: https://github.com/rofrba/gitops-kustomize.git
    targetRevision: develop
    path: apps
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-gitops
  syncPolicy:
    automated:
      prune: true
      selfHeal: true