apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-kustomize-webapp
  labels:
    app: hello-kustomize-webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello-kustomize-webapp
  template:
    metadata:
      labels:
        app: hello-kustomize-webapp
    spec:
      containers:
      - name: hello-kustomize-webapp
        image: pcrete/gitops-argocd-demo:master-e66424e2
        ports:
          - containerPort: 5005
            protocol: TCP
        env:
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: spec.nodeName
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.namespace
          - name: POD_NAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: metadata.name
          - name: POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
        securityContext: {}
        imagePullPolicy: IfNotPresent
        resources: 
          requests:
            memory: 128Mi
            cpu: 20m
          limits:
            memory: 128Mi
            cpu: 20m