apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-22
  namespace: openshift-gitops
  labels:
    test: scale
spec:
  project: default
  source:
    repoURL: https://github.com/rofrba/gitops-kustomize.git # Usa tu propio repo de prueba
    targetRevision: develop
    path: .
    kustomize:
      namePrefix: app-22-
  destination:
    server: https://kubernetes.default.svc # Esto se reemplazará
    namespace: test-apps-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true